name: Android CI / Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Prepare Sentry Properties
      run: |
        echo "defaults.org=netrator" > sentry.properties
        echo "defaults.project=omnis-mobile" >> sentry.properties
        echo "auth.token=${{ secrets.SENTRY_AUTH_TOKEN }}" >> sentry.properties

    - name: Build APKs
      run: ./gradlew assembleDebug assembleRelease
      env:
        SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

    - name: Rename and Prepare APKs
      if: github.event_name == 'release'
      run: |
        VERSION_NAME=$(grep -oP 'versionName = "\K[^"]+' app/build.gradle.kts)
        
        # Release APK
        mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/omnis-mobile-v${VERSION_NAME}-release.apk
        
        # Debug APK
        mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/omnis-mobile-v${VERSION_NAME}-debug.apk
        
        echo "RELEASE_APK=app/build/outputs/apk/release/omnis-mobile-v${VERSION_NAME}-release.apk" >> $GITHUB_ENV
        echo "DEBUG_APK=app/build/outputs/apk/debug/omnis-mobile-v${VERSION_NAME}-debug.apk" >> $GITHUB_ENV

    - name: Upload APKs to Release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ${{ env.RELEASE_APK }}
          ${{ env.DEBUG_APK }}
